# Generated by Django 6.0.1 on 2026-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('weather', 'Weather'), ('war', 'War'), ('global', 'Global'), ('ethiopia', 'Ethiopia'), ('africa', 'Africa'), ('business', 'Business'), ('job', 'Job vacancy')], default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
