# Generated by Django 6.0.1 on 2026-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_published_at_news_created_at_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
