# Generated by Django 6.0.1 on 2026-03-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
    ]
